server:
    port: 8081
    servlet:
        contextPath: /payments-genai-hackathon-pay-pros-backend/v1
spring:
    ai:
        azure:
            openai:
                apiKey: <<API_KEY>>
                endpoint: https://payprosoai4.openai.azure.com/
                chat:
                    options:
                        deploymentName: PayProsOAIDeployment

azure:
    storage:
        connection-string: your-azure-storage-connection-string
        container-name: your-container-name
    document-intelligence:
        api-url: https://document-ai1.cognitiveservices.azure.com/
        api-key: 389f4231d5bc440abac9fdc10d96a5d1